version: '3.9'
services:
  aqarino-backend:
    build: ./backend
    container_name: aqarino-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./aqarino_v2.db
      - LEAD_OUTPUT=excel

  frontend:
    image: nginx:alpine
    container_name: aqarino-frontend
    ports:
      - "8081:80"
    volumes:
      - ./backend/app/static/host:/usr/share/nginx/html:ro
